#!/bin/sh
if [ "$1" == "" ]
then
  echo "Usage: query <module>"
  echo "Example: query io/console"
  exit 1
fi

# Get module name
modulename="${1##*/}"
dirname="$(dirname ${1})"

if [ "${1: -3}" != ".if" ]
then
  filename=${1}.rs
  ifacename=${1}.if
else
  filename=${1:0:-3}.rs
  ifacename=${1}

  modulename="${modulename:0:-3}"
fi

if [ ! -e "${ifacename}" ]
then
  echo "error: interface not found for ${modulename}"
  exit 1
else
  echo "     interface: ${ifacename}"
fi

if [ -e "../ibis/${filename}" ]
then
  echo "implementation: ../ibis/${filename}"
fi

existing_lib=`ls ../ibis/.libs/lib${modulename}-*.so 2> /dev/null`
if [ -e $existing_lib ]
then
  echo "      compiled: ${existing_lib}"
fi

if [ -e "../spec/${filename}" ]
then
  echo " specification: ../spec/${filename}"
fi
